name: drwz
on: push
jobs:
  Build-et-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Build de l'image drwz
        run: docker build -t drwz:latest .

      - name: Scan de l'image avec Trivy
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image \
            --ignore-unfixed --severity HIGH,CRITICAL --exit-code 1 drwz1.3:latest
